"""initial migration

Revision ID: 1ba1c83de34c
Revises: 
Create Date: 2026-04-12 18:58:31.355951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba1c83de34c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_variant_consequence', 'variant_cache', ['consequence'], unique=False)
    op.create_index('idx_variant_impact', 'variant_cache', ['impact'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_variant_impact', table_name='variant_cache')
    op.drop_index('idx_variant_consequence', table_name='variant_cache')
    # ### end Alembic commands ###
