"""add v2 clinical fields

Revision ID: 453a3747ceb7
Revises: 7552cb4e3125
Create Date: 2026-05-01 19:02:11.218167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453a3747ceb7'
down_revision: Union[str, None] = '7552cb4e3125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_cache', sa.Column('clinvar_significance', sa.String(), nullable=True))
    op.add_column('variant_cache', sa.Column('clinvar_review_stars', sa.Integer(), nullable=True))
    op.add_column('variant_cache', sa.Column('gnomad_af_popmax', sa.Float(), nullable=True))
    op.add_column('variant_cache', sa.Column('acmg_tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_cache', 'acmg_tier')
    op.drop_column('variant_cache', 'gnomad_af_popmax')
    op.drop_column('variant_cache', 'clinvar_review_stars')
    op.drop_column('variant_cache', 'clinvar_significance')
    # ### end Alembic commands ###
