"""add hgvs fields to variant_cache

Revision ID: 7552cb4e3125
Revises: 1ba1c83de34c
Create Date: 2026-05-01 16:57:14.295294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7552cb4e3125'
down_revision: Union[str, None] = '1ba1c83de34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_cache', sa.Column('hgvsc', sa.String(), nullable=True))
    op.add_column('variant_cache', sa.Column('hgvsp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_cache', 'hgvsp')
    op.drop_column('variant_cache', 'hgvsc')
    # ### end Alembic commands ###
